### Crawler

Date: 2016-08-23<br>
Writer: Sundong Kim<br>
1. Python porting of sojin/Craw.java 
2. shops/781(커스텀멜로우 홍대점), shops/786(코오롱 스포츠 문정직영점)에 대해 크롤링함

In [51]:
### import libraries
import urllib.request, json, re
import pandas as pd
import datetime
import time, calendar

Final recorded timestep: 1456109531149 : 02/22/2016 @ 2:52am (UTC)

시간에 관한 코드들 (참고용)

In [170]:
datetime.datetime.now()

datetime.datetime(2016, 8, 23, 16, 55, 22, 71386)

In [188]:
time.time()*1000

1471939310111.688

In [200]:
since = ((0x7FFFFFFFFFFFFFFF - (time.time() * 1000)*0x1000))

In [198]:
print(hex(int(since)))

0x7fea949945e89800

In [196]:
print (0x1000)

4096

In [70]:
urlstrip1 = "http://walkinsights.com/api/v1/shops/781/sessions?"
urlstrip2 ="limit=1000&user_token=77eFJPB37UkgYyLjWZrx&user_email=jeeyeachung@kolon.com"
url = urlstrip1 + urlstrip2
response = urllib.request.urlopen(url)
str_response = response.read().decode('utf-8')
obj = json.loads(str_response)

In [71]:
obj['since']

'7fea948bd7618f4b:out'

In [57]:
with open('../data/786/786_7fea948e02dd1c3c:out.json', 'w') as f:
    json.dump(obj, f)
f.close()

In [58]:
# ts = obj['sessions'][-1]['key']
# ts = ts.split(':')[1]
# ts
ts = obj['since']
ts

'7fea948e02dd1c3c:out'

In [59]:
while(True):
    urlstrip3 = "since="+ts+"&limit=1000&"
    url = urlstrip1 + urlstrip3 + urlstrip2
    response = urllib.request.urlopen(url)
    str_response = response.read().decode('utf-8')
    obj2 = json.loads(str_response)
    filename = '../data/786/786_'+ts+'.json'
    with open(filename, 'w') as f:
        json.dump(obj2, f)
    f.close()
    ts = ts = obj2['since']

KeyError: 'since'

In [69]:
### check the last json file has 'since' key or not -- shouldn't have.

with open('../data/786/786_7feb08df832c48f0:out.json', 'r') as f:
    obob = json.load(f)
    f.close()
obob.keys()

dict_keys(['sessions'])

In [73]:
with open('../data/786/786_7fea9a0c3e00bff2:out.json') as f:
    d = json.load(f)
    df = pd.DataFrame(d['sessions'])
df.tail(5)

,area,deny,device_id,dwell_time,key,revisit_count,revisit_period,ts
995,out,NaN,30773249e9e0d008c3740a74619516f3,0,786:7fea9a1028756efe:out,NaN,NaN,1470472485033
996,out,NaN,27401baaf80613ef30573e2a877504f6,56,786:7fea9a102899bc70:out,NaN,NaN,1470472484452
997,out,NaN,f3414eefe9d48da7f62f3ddb42bd9594,0,786:7fea9a1029b1fef5:out,NaN,NaN,1470472479968
998,out,NaN,a74734a14e8b6de13f3094bfc5c3ff9f,198,786:7fea9a1029d72e37:out,NaN,NaN,1470472479373
999,out,NaN,4d6cb2f9a480fbe2f386bb38b902c5a4,55,786:7fea9a102a42ac4e:out,NaN,NaN,1470472477653

In [211]:
d['since']

'7feacfdd855251ab:man-right'

In [74]:
import glob
import os

In [75]:
contents = []
files = glob.glob('../data/786/*.json')
for filename in files:
    with open(filename, 'r') as f:
        d = json.load(f)
        contents.extend(d['sessions'])

df = pd.DataFrame(contents)
    
#         d = json.load(f)
#         df = pd.DataFrame(d['sessions'])
#     df.tail(5)

In [76]:
device_ids = df['device_id'].unique()
print (len(device_ids))
print (df.shape)

616346
(4038290, 8)

In [77]:
df

,area,deny,device_id,dwell_time,key,revisit_count,revisit_period,ts
0,out,NaN,d4b789e1ce0c640c985872d98ea8f27e,0,786:7fea948e02dd1c3c:out,NaN,NaN,1471951131182
1,out,NaN,6250716737534c6c8a365f5306faf014,0,786:7fea948e03709f8a:out,2.0,55.0,1471951128822
2,out,NaN,098b481a59f84a0fb50ab818d076f9a3,2,786:7fea948e0449ceac:out,1.0,78.0,1471951125347
3,out,NaN,a5fcb9dfa9e7fd724e18607b9faddaf7,265,786:7fea948e057f5c34:out,NaN,NaN,1471951120394
4,out,NaN,e0689c2410660db5d9404310828d2886,0,786:7fea948e05828da7:out,NaN,NaN,1471951120343
5,out,NaN,8ffbe5d4075bd0c748ad2f526bbf2ce2,0,786:7fea948e07745e50:out,NaN,NaN,1471951112378
6,out,NaN,e81b6eeb1768f43979e32fb64cc7d62b,0,786:7fea948e07d75f65:out,NaN,NaN,1471951110794
7,out,True,aa521dace7352fe65182259a2f6a03d7,2714,786:7fea948e07f77faf:out,NaN,NaN,1471951110280
8,out,NaN,2b52692f3fe846050898278e65f8619f,0,786:7fea948e0816ce93:out,1.0,8.0,1471951109779
9,out,True,dd08b6b8bd12f4f55b5b3b8b14710f81,0,786:7fea948e087aedce:out,1.0,5.0,1471951108177
10,out,NaN,c6d89ef96a636d9c78e0b833fb0af0ff,4,786:7fea948e08930c33:out,NaN,NaN,1471951107791
11,out,NaN,39c20ef4c678dcb50ba3738587fff20e,47,786:7fea948e09c12dae:out,NaN,NaN,1471951102957
12,out,NaN,0a745e50a23633ee3d44f399bcaebbd1,0,786:7fea948e0a2bac2c:out,NaN,NaN,1471951101253
13,out,NaN,e0b3dfc2ba1b25a5a7c3cb92e9415cf2,0,786:7fea948e0af46d4a:out,NaN,NaN,1471951098041
14,out,NaN,98540735538c087958fb5df444e6972f,0,786:7fea948e0d7f2c3f:out,NaN,NaN,1471951087629
15,2f,True,9fb53edfa51e283d01a47b76af41bc13,2159,786:7fea948e107f8c69:2f,NaN,NaN,1471951075335
16,in,True,9fb53edfa51e283d01a47b76af41bc13,2159,786:7fea948e107f8c69:in,NaN,NaN,1471951075335
17,out,NaN,ce74f9a87d5805408dd98206a6f57876,10,786:7fea948e10d5dfbb:out,2.0,5.0,1471951073954
18,out,NaN,d898c199ad260318f9357d3af1b1a861,0,786:7fea948e112e0ce6:out,NaN,NaN,1471951072543
19,out,NaN,67c56b913804d0797ba5ca8563fe83d7,8,786:7fea948e11662fe1:out,NaN,NaN,1471951071645
20,out,NaN,24b871672fee0cf2a0f94a457f363c2d,3,786:7fea948e11d29d22:out,1.0,17.0,1471951069910
21,out,NaN,577f31030d110b9ffff761741fded72e,5111,786:7fea948e11d36cc3:out,1.0,1.0,1471951069897
22,out,NaN,44adef5f5dbbfcc9c0b3df7587d8b58b,18,786:7fea948e133dde56:out,NaN,NaN,1471951064098
23,out,NaN,d6fda1d2a825f1966aef59e6841eb7ed,0,786:7fea948e137b6ffe:out,NaN,NaN,1471951063113
24,out,True,71c27198a8088c4b2ae981ef7729df91,17,786:7fea948e14dddfa3:out,NaN,NaN,1471951057442
25,out,True,dd988ea5fea254a96786221196835ded,0,786:7fea948e18ccbfba:out,NaN,NaN,1471951041332
26,out,NaN,4e442f57aa5ad571f956038368c96e82,0,786:7fea948e18fcbd6a:out,2.0,39.0,1471951040564
27,out,NaN,25fc57a9d8f9142c216a8a0ffacaa19b,267,786:7fea948e19409d59:out,23.0,5.0,1471951039478
28,out,NaN,2fc1eca2f72b9862716dedd325733f9b,0,786:7fea948e1a462e51:out,NaN,NaN,1471951035293
29,out,True,91b05442085d7b1d75e8dfdc8e141c79,463,786:7fea948e1b09cdf4:out,NaN,NaN,1471951032163
...,...,...,...,...,...,...,...,...
4038260,out,NaN,79973d410bf60f10b0e23d88fb5a65a2,4,786:7feb08e15182a5f7:out,NaN,NaN,1440725264341
4038261,out,NaN,953811f9bd8223e6f35905be86e37012,0,786:7feb08e1564ff5b8:out,NaN,NaN,1440725244672
4038262,out,NaN,b4d3498eeb12fbdf4d3a5ef0a47445a6,5,786:7feb08e1596b17c9:out,NaN,NaN,1440725231950
4038263,out,NaN,842e0a1aae59e8fd4a4bce865b389524,0,786:7feb08e1614318b7:out,NaN,NaN,1440725199822
4038264,out,NaN,9442d900a14b3682a7eeff01dffb4786,1055,786:7feb08e165c9a0a4:out,NaN,NaN,1440725181285
4038265,out,NaN,4961fa00a245ae52954dedbcf8c68f45,3270,786:7feb08e166e21c3a:out,NaN,NaN,1440725176798
4038266,out,NaN,028a1f4dbca00ed06814fdda60f1b599,3548,786:7feb08e16727e4a9:out,NaN,NaN,1440725175681
4038267,out,NaN,fa1f5d08eba95839db76ecbb97619c0b,48776,786:7feb08e16772c49d:out,NaN,NaN,1440725174483
4038268,out,NaN,84634b694d34053594bfd5fcbb2b5220,17,786:7feb08e16781d39e:out,NaN,NaN,1440725174242
4038269,out,NaN,3a45b9cb885ee694c6c0b2a96a87468f,48815,786:7feb08e1692d378c:out,NaN,NaN,1440725167404
4038270,out,NaN,d8d837f07fa661baafae573324c45b96,50,786:7feb08e16b2cb8c0:out,NaN,NaN,1440725159220
4038271,out,NaN,f0652d4665d8f00c35a3b01a7699a6ce,16,786:7feb08e16b6ffcf6:out,NaN,NaN,1440725158144
4038272,out,NaN,ca112676b76f0fe90ddee740b0459a97,48652,786:7feb08e16ce944c5:out,NaN,NaN,1440725152107
4038273,out,NaN,54dfd78bf25c32eb0e5a3cd1bc9460bd,37916,786:7feb08e16feafb07:out,NaN,NaN,1440725139792
4038274,out,True,ec588edbcb0b6975125e3c441a389381,35156,786:7feb08e170fd081e:out,NaN,NaN,1440725135407
4038275,out,NaN,a6b7b09b93de015cd27da23cbd6c093c,3400,786:7feb08e17126e4b4:out,NaN,NaN,1440725134737
4038276,out,True,1bb57295fdd527202a1aeac3e29b9504,24386,786:7feb08e172b1edb2:out,NaN,NaN,1440725128417
4038277,1f,True,47cbc1c26d0aa075de241967ac014e51,3433,786:7feb08e173f3f93e:1f,NaN,NaN,1440725123264
4038278,in,True,47cbc1c26d0aa075de241967ac014e51,3433,786:7feb08e173f3f93e:in,NaN,NaN,1440725123264
4038279,out,True,47cbc1c26d0aa075de241967ac014e51,48403,786:7feb08e173f3f93e:out,NaN,NaN,1440725123264
4038280,out,True,678811f2ba54a0ab8b1738e61bcf6ea1,7230,786:7feb08e1745c7231:out,NaN,NaN,1440725121592
4038281,1f-inner,True,3cb3c5d41981dcf7f75ffc1db3378c6e,37968,786:7feb08e174a3b768:1f-inner,NaN,NaN,1440725120452
4038282,out,NaN,c9866cd15a94b493feb0c2816826bc8d,3971,786:7feb08e17538ce25:out,NaN,NaN,1440725118067
4038283,out,NaN,6196c10f70d67f258476bde25fc738c4,0,786:7feb08e1758ab2e1:out,NaN,NaN,1440725116756
4038284,1f,True,3cb3c5d41981dcf7f75ffc1db3378c6e,37975,786:7feb08e1758f3ee2:1f,NaN,NaN,1440725116684
4038285,in,True,3cb3c5d41981dcf7f75ffc1db3378c6e,37975,786:7feb08e1758f3ee2:in,NaN,NaN,1440725116684
4038286,out,True,3cb3c5d41981dcf7f75ffc1db3378c6e,37975,786:7feb08e1758f3ee2:out,NaN,NaN,1440725116684
4038287,1f,NaN,3a256162262ef2f26d547642036db82b,497,786:7feb08e1761b65c6:1f,NaN,NaN,1440725114441
4038288,in,NaN,3a256162262ef2f26d547642036db82b,497,786:7feb08e1761b65c6:in,NaN,NaN,1440725114441
4038289,out,NaN,3a256162262ef2f26d547642036db82b,3207,786:7feb08e1761b65c6:out,NaN,NaN,1440725114441

In [78]:
df.to_pickle("../data/786/786.p")

다른 분석 등은 Analysis.ipynb 참고

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3962136 entries, 0 to 3962135
Data columns (total 8 columns):
area              object
deny              object
device_id         object
dwell_time        int64
key               object
revisit_count     float64
revisit_period    float64
ts                int64
dtypes: float64(2), int64(2), object(4)
memory usage: 241.8+ MB

In [49]:
df.loc[:,"revisit_count"].value_counts(ascending=True)

85.0        27
82.0        27
83.0        42
84.0        58
86.0        94
81.0       161
87.0       176
58.0       259
48.0       271
56.0       274
62.0       281
60.0       281
42.0       298
68.0       309
43.0       319
64.0       324
63.0       328
70.0       329
80.0       366
40.0       367
79.0       370
39.0       373
41.0       378
44.0       378
50.0       379
38.0       379
45.0       387
34.0       391
46.0       412
37.0       412
         ...
27.0       613
22.0       619
16.0       671
20.0       671
19.0       687
77.0       747
76.0       748
57.0       824
18.0       854
15.0       859
78.0       991
90.0       993
13.0      1034
12.0      1130
14.0      1134
74.0      1428
75.0      1513
88.0      1619
10.0      1622
89.0      1654
11.0      1661
9.0       2330
8.0       2696
7.0       3670
6.0       3944
5.0       5158
4.0      10239
3.0      17591
2.0      35772
1.0     149888
Name: revisit_count, dtype: int64